# serverless.yml

service: hang

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128

plugins:
#  - serverless-localstack
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
#  pythonRequirements:
#    dockerizePip: non-linux
#    layer: true
#  localstack:
#    debug: true
#    stages:
#      # list of stages for which the plugin should be enabled
#      - local
#    host: http://localhost  # optional - LocalStack host to connect to
#    autostart: true  # optional - start LocalStack in Docker on Serverless deploy
##    endpoints:
#      # This section is optional - can be used for customizing the target endpoints
##      S3: http://localhost:4572
##      DynamoDB: http://localhost:4569
##      CloudFormation: http://localhost:4581
##      Elasticsearch: http://localhost:4571
##      ES: http://localhost:4578
##      SNS: http://localhost:4575
##      SQS: http://localhost:4576
##      Lambda: http://localhost:4574
##      Kinesis: http://localhost:4568
##      APIGateway: http://localhost:4567
##    lambda:
#      # Enable this flag to improve performance
##      mountCode: True
#    docker:
#      # Enable this flag to run "docker ..." commands as sudo
#      sudo: False
##  stages:
##    - local
#package:
#  individually: true

functions:
  app:
    handler: wsgi_handler.handler
#    package:
#      artifact: serverlessmr-web.zip
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - node_modules/**
    - templates/static/node_modules/**