version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=lambda,s3
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
#      - LOCALSTACK_HOSTNAME=Hangs-MacBook-Pro.local
      - DEBUG=1
#      - SERVICES=${SERVICES- }
#      - SERVICES=s3,lambda
#      - DEBUG=${DEBUG- }
#      - DATA_DIR=${DATA_DIR- }
#      - PORT_WEB_UI=${PORT_WEB_UI- }
#      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
#      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
#      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
